name: Build Awais Trading Bot APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'  # You can change to the version you're using

    - name: Install dependencies
      run: flutter pub get

    - name: Build release APK
      run: flutter build apk --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: AwaisBot-Release-APK
        path: build/app/outputs/flutter-apk/app-release.apk
